/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package weathershow;

import javax.swing.SwingUtilities;

/**
 *
 * @author Chazz
 */
public class WeatherShowSettings extends javax.swing.JDialog {

	private int minRefreshInterval = 1;
	private int maxRefreshInterval = 24;
	private WeatherShowView wsv;
	private Settings settings;

	/**
	 * Creates new form WeatherShowSettings
	 */
	public WeatherShowSettings(java.awt.Frame parent) {
		super(parent, true);

		wsv = (WeatherShowView) parent;
		settings = new Settings(wsv);
		settings.load();
		initComponents();
	}

	private String[] getLAFModel() {
		String[] lafs = new String[javax.swing.UIManager.getInstalledLookAndFeels().length];
		int i = 0;
		for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			lafs[i] = info.getName();
			i++;
		}
		return lafs;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        refreshIntervalField = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hideOnMinimizeField = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        hideOnCloseField = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        lafField = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        tempUnitsField = new javax.swing.JComboBox();
        distUnitsField = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

        jLabel1.setText("Refresh interval");

        refreshIntervalField.setModel(new javax.swing.SpinnerNumberModel(3, minRefreshInterval, maxRefreshInterval, 1));
        refreshIntervalField.setValue((settings.getRefreshInterval()/60/60/1000));
        refreshIntervalField.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                refreshIntervalFieldMouseWheelMoved(evt);
            }
        });

        jLabel2.setText("Hours");

        jLabel3.setText("Hide on minimize ");

        hideOnMinimizeField.setSelected(settings.isHideOnMinimize());

        jLabel4.setText("Hide on close");

        hideOnCloseField.setSelected(settings.isHideOnClose());

        jLabel5.setText("Look and feel");

        lafField.setModel(new javax.swing.DefaultComboBoxModel(getLAFModel()));
        lafField.setSelectedItem(settings.getLaf());
        lafField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lafFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Temperature units");

        tempUnitsField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celsius", "Fahrenheit" }));
        tempUnitsField.setSelectedItem(settings.getTempUnits());

        distUnitsField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kilometers", "Miles" }));
        distUnitsField.setSelectedItem(settings.getDistUnits());

        jLabel7.setText("Distance units");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hideOnMinimizeField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(refreshIntervalField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hideOnCloseField)
                            .addComponent(lafField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(distUnitsField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempUnitsField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(refreshIntervalField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tempUnitsField)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(distUnitsField)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lafField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hideOnMinimizeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hideOnCloseField)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(saveButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void refreshIntervalFieldMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_refreshIntervalFieldMouseWheelMoved
		int currentValue = Integer.parseInt(refreshIntervalField.getValue().toString());
		int rotation = evt.getWheelRotation();
		int newValue = currentValue - rotation;
		if (newValue >= minRefreshInterval && newValue <= maxRefreshInterval) {
			refreshIntervalField.setValue(newValue);
		}
	}//GEN-LAST:event_refreshIntervalFieldMouseWheelMoved

	private void lafFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lafFieldActionPerformed
		WeatherShowView.setLAF(lafField.getSelectedItem());
		SwingUtilities.updateComponentTreeUI(wsv);
		SwingUtilities.updateComponentTreeUI(this);
		wsv.pack();
		pack();
	}//GEN-LAST:event_lafFieldActionPerformed

	private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		String laf = lafField.getSelectedItem().toString().trim();
		String distUnits = distUnitsField.getSelectedItem().toString().trim();
		String tempUnits = tempUnitsField.getSelectedItem().toString().trim();
		int refreshINtervalHours = Integer.parseInt(refreshIntervalField.getValue().toString().trim());
		long refreshInterval = refreshINtervalHours * 60 * 60 * 1000;
		boolean hideOnClose = hideOnCloseField.isSelected();
		boolean hideOnMinimize = hideOnMinimizeField.isSelected();
		settings.save(laf, distUnits, tempUnits, refreshInterval, hideOnClose, hideOnMinimize);
		wsv.setNewSettings();
		
		dispose();
	}//GEN-LAST:event_saveButtonActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		WeatherShowView.setLAF(settings.getLaf());
		SwingUtilities.updateComponentTreeUI(wsv);
		SwingUtilities.updateComponentTreeUI(this);
		wsv.pack();
		dispose();
	}//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox distUnitsField;
    private javax.swing.JCheckBox hideOnCloseField;
    private javax.swing.JCheckBox hideOnMinimizeField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox lafField;
    private javax.swing.JSpinner refreshIntervalField;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox tempUnitsField;
    // End of variables declaration//GEN-END:variables
}
